name: 'Build and Tests'
on:
  push:

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: PNPM Install
        run: 'npm install -g pnpm'

      - name: Install Dependencies
        run: 'pnpm install --frozen-lockfile'

      - name: Playwright Install
        run: 'pnpm exec playwright install'

      - name: Set env
        run: echo "DATABASE_URL=file:../data/GetItDone.db" >> $GITHUB_ENV
      - run: pnpm prisma:generate
      - run: pnpm prisma:migrate

      - name: Run Tests
        run: 'pnpm test'

  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: PNPM Install
        run: 'npm install -g pnpm'

      - name: Install Dependencies
        run: 'pnpm install --frozen-lockfile'

      - name: Test Build
        run: 'pnpm build'
